disable_disk_cache: BOOL
destination: E://website
port: 1234
title: ubX's Site
email: ubX@outlook.in
description: >-
  Akshay is a human, lol

baseurl: "/"

default:
  - scope:
      path: ""
      type: "post"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-paginate

plugins: [jekyll-paginate]
paginate: 11
paginate_path: "/posts/page-:num/"

kramdown:
  auto_ids: true
  toc_levels: 1..3
  # parse_block_html: true
